### ISSUE TITLE
Why lazy option and lazy either occupied default namings instead of strict ?

### ISSUE THREAD

**Issue by Badmoonz** [louthy/csharp-monad#14]
I'm a bit confused with the fact that more idiomatic and usable implementation(-strict) of that data types got complex names.

**Comment by louthy** [comment]
Not sure I totally agree with your statement that the lazy versions are non-idiomatic.  The only monads in the BCL: `IQueryable<T>` and `IEnumerable<T>` are both lazy.  

If you want strict versions that are named as you would like you could try my other library Language-Ext: https://github.com/louthy/language-ext (it has much better implementations of monads in general anyway) - Although if you're dogmatically attached to idioms then you're probably not going to like that library too much either ;-) 

The use of monads and the functional 'style' is basically non-idiomatic by default in C#, even `IEnumerable<T>` and `IQueryable<T>` try to 'cover up' their origins.  So when it comes to developing functional libraries or frameworks for C# I'm prefer to go with the idioms of F# or Haskell and functional languages in general.

**Comment by Badmoonz** [comment]
Thx for the answer :)
Sorry for the angry tone of my first post. Just was annoyed that day by my newbie(no expirience at any other fp lang) teammates choosing you monad lib over mine own C#  fp-tooling lib(that I was argued them to use to increase safeness of code more than HALF A YEAR and successefully applied in many parts of project by myself). Their main argument was that word `computation` is met in difinition of monad stolen from wiki , then all monads should work as delayed computations /facepalm. 
And as I see for 99% problems delayed computations has unnecessary complexity and hide enough danger of uncarefull usage for such primitive data types as option and either.

Fairly at the begining of my own lib, I had a short look at your code at https://github.com/louthy/language-ext ;)

**Comment by Badmoonz** [comment]
Also I have a nice implementation of Discriminated Unions with flexible and type-strict pattern matching, maybe will send pullrequest to https://github.com/louthy/language-ext  for review
