### ISSUE TITLE
Either and EitherStrict Generic Parameter ordering

### ISSUE THREAD

**Issue by thedillonb** [louthy/csharp-monad#4]
First off, great library. Thank you for publishing this. My only concern is with the ordering of the generic parameter ordering for `Either<R, L>` and `EitherStrict<R, L>`. Visually, it's confusing to see the left argument of the generic be the right and vise versa. It seems to make the following very counter intuitive:

```
Either.Right<string, bool>(() => "Hello!");
```

From a purely directional standpoint I think it might make more sense to reverse their ordering and use `<L, R>`. That way

```
Either.Right<string, bool>(() => false);
```

Refers, not only to the right generic argument, but also the right monad.

**Comment by louthy** [comment]
I have finally come around to this thinking, I always had in my mind that the 'subject' of the monad would be first in the list of generic arguments.  On my other library on here (language-ext), I did the same.  

It previously felt odd having this:
```C#
    Either<Error,int>
````
But I am finally convinced that actually for readability sake you do want the Right on the right and the Left on the left.

The changes are checked in, I will do a new release and nuget package soon.  Thanks for the feedback :)

**Comment by thedillonb** [comment]
Awesome @louthy, thanks a lot!
