### ISSUE TITLE
AsEnumberableInfinte - a typo?

### ISSUE THREAD

**Issue by orthoxerox** [louthy/csharp-monad#9]
Should it be called `AsEnumerableInfinite` instead?

**Comment by ApocalypticOctopus** [comment]
Good catch. Output from `grep -r "Infinte" .`:

    ./CSharpMonad/src/EitherLazy.cs:        public static IEnumerable<R> AsEnumerableInfinte<L, R>(this Either<L, R> self)
    ./CSharpMonad/src/EitherStrict.cs:        public IEnumerable<R> AsEnumerableInfinte()
    ./CSharpMonad/src/option-lazy/Option.cs:        public static IEnumerable<T> AsEnumerableInfinte<T>(this Option<T> self)
    ./CSharpMonad/src/option-strict/OptionStrict.cs:        public IEnumerable<T> AsEnumerableInfinte()

**Comment by louthy** [comment]
Fixed
